### ISSUE TITLE
Support ignoring users who unshared from a calendar

### ISSUE THREAD

**Issue by tcitworld** [nickv-nextcloud/event_update_notification#100]
https://github.com/nextcloud/server/pull/43117 brings a new share type which needs to be taken into account.

**Comment by tcitworld** [comment]
What we need is the list of unshares for a calendar, so that we can remove them from the list of users computed from the group shares.

As far as I can see there's no way to get the list of shares *including* the unshares, so this needs server changes. I would either :
- `getSharesForId` to have an optional parameter to include unshares
- add a new method to get specifically unshares

Do you have some input @miaulalala ?

**Comment by nickvergessen** [comment]
I'll have a look

**Comment by miaulalala** [comment]
> What we need is the list of unshares for a calendar, so that we can remove them from the list of users computed from the group shares.
> 
> As far as I can see there's no way to get the list of shares _including_ the unshares, so this needs server changes. I would either :
> 
>     * `getSharesForId` to have an optional parameter to include unshares
> 
>     * add a new method to get specifically unshares
> 
> 
> Do you have some input @miaulalala ?

I like the unshares method. Optional params are not my fave code construct. OTOH having one query instead of two is a legitimate thought. I leave the implementation details up to you.
