### ISSUE TITLE
Please make the app compatible with NC19

### ISSUE THREAD

**Issue by szaimen** [nickv-nextcloud/event_update_notification#15]
Hi,

it seems like the app wasn't updated for NC19.
Please make it compatible.

Thanks!

**Comment by nickvergessen** [comment]
You can try adjusting the appinfo/info.xml to see if that works.

**Comment by nickvergessen** [comment]
@szaimen worked?

**Comment by szaimen** [comment]
Yes, the apps seems to work in NC19. It only needs a release for 19 over the store.

**Comment by rakekniven** [comment]
Today is release day, or?

**Comment by nickvergessen** [comment]
Well today it is, but I have quite some apps I maintain so it can just take some time:
https://apps.nextcloud.com/?maintainer=nickvergessen

**Comment by rakekniven** [comment]
Didn't think there would be so many 😱 

Really appreciate the work you do!

**Comment by nickvergessen** [comment]
1.0.2 is published in the appstore now:
https://apps.nextcloud.com/apps/event_update_notification/releases?platform=19#19
