### ISSUE TITLE
Calendar notifications appear even if app is disabled or uninstalled

### ISSUE THREAD

**Issue by kruthoff** [nickv-nextcloud/event_update_notification#16]
After a while, I wanted to get rid of the calendar event notifications in my Nextcloud.

I've disabled the app - calendar notifications still appear.
I've uninstalled the app - calendar notification still appear.

Calendar notification feature can't be switched off, if it was installed once. This looks like a bug.

Nextcloud 18, postgres, nginx.

**Comment by nickvergessen** [comment]
Can you post a screenshot of the notifications you still receive?
Also can you post your app list (run `php occ app:list`)

**Comment by kruthoff** [comment]
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - audioplayer: 2.10.1
  - audioplayer_editor: 0.2.2
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.7
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - drawio: 0.9.6
  - drop_account: 0.2.1
  - end_to_end_encryption: 1.4.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_fulltextsearch: 1.4.2
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.2
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - guests: 1.4.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.2
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - circles
  - encryption
  - files_external
  - jsloader
  - socialsharing_email
  - socialsharing_twitter
  - user_ldap

**Comment by kruthoff** [comment]
![notify](https://user-images.githubusercontent.com/2143006/87218837-b46f0580-c356-11ea-92fb-47b2004c1a9d.png)

**Comment by nickvergessen** [comment]
This is not from this app.
Do you know which app it is, @georgehrke ?

**Comment by georgehrke** [comment]
> I've disabled the app - calendar notifications still appear.
> I've uninstalled the app - calendar notification still appear.
>
> Calendar notification feature can't be switched off, if it was installed once. This looks like a bug.

The Calendar App is just a UI for Nextcloud's CalDAV server. The actual CalDAV server is part of the dav app, which can't be disabled. (This also means that all your events are still stored inside the Nextcloud server).

If you would like to disable event reminders:
1. Go to settings
2. Go to Groupware (Administration section)
3. Disable the "Send notifications for events" option
