### ISSUE TITLE
Set "Enable notifications for events via push" to true via occ

### ISSUE THREAD

**Issue by floatingpurr** [nickv-nextcloud/event_update_notification#17]
Hello, I'm wondering if there's a way to mark the setting _Enable notifications for events via push_ via occ or with other command line options, without using the Web GUI

**Comment by nickvergessen** [comment]
This app does not have such a setting. Can you add a screenshot what you are talking about?

**Comment by floatingpurr** [comment]
Hey @nickvergessen, thanx for your help. I mean Settings > Groupware > [Enable notifications for events via push](https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#reminder-notifications). Maybe is more related to calendar than to notifications itself...

**Comment by nickvergessen** [comment]
Yeah it's unrelated to the functionality of this app.

**Comment by nickvergessen** [comment]
Can you crwate an issue in the calendar?

**Comment by floatingpurr** [comment]
Yes! Excuse me for the inconvenience
