### ISSUE TITLE
Difference between this app and the activity setting

### ISSUE THREAD

**Issue by jakobroehrl** [nickv-nextcloud/event_update_notification#19]
What is the difference between this app and this activity setting?
![image](https://user-images.githubusercontent.com/24530680/117628203-2e3f6d80-b179-11eb-8bbe-cc561afb2716.png)

**Comment by nickvergessen** [comment]
This app is from long before activity allowed pushes or calendar creates notifications/activities at all.

The other difference is the message that is sent, for this app it shows the date+time of the next occurrence, the plain activities don't contain any such information. But this is the main usecase for me with my wife.
Knowing she added/updated an event is step 1, but the more important thing is to get to know when the event is happening.

**Comment by jakobroehrl** [comment]
@nickvergessen Thanks. This is my use case, too. :)
My problem is this: https://help.nextcloud.com/t/notification-on-shared-calendars-isnt-working-any-more/115641
That's why I swichted back to this app, and with that it works again.

**Comment by nursoda** [comment]
Consider a larger user base of a club and some club officials. In my case, the calendar is used to book a resource (video conferencing license).

The activity setting doesn't help as it doesn't allow to distinguish between the official's ordinary planning calendars and that one ressource booking calendar. Neither does this app.

Plus, this app does not allow to restrict which users should receive notifications. In my case, >400 users would get messages although only one person needs them.

So, currently we need to instruct users to e-mail the officials what they booked or changed. This app does have to potential to solve this, but I don't have to knowledge to implement the UI necessary.

**Comment by jakobroehrl** [comment]
> This app is from long before activity allowed pushes or calendar creates notifications/activities at all.
> 
> The other difference is the message that is sent, for this app it shows the date+time of the next occurrence, the plain activities don't contain any such information. But this is the main usecase for me with my wife. Knowing she added/updated an event is step 1, but the more important thing is to get to know when the event is happening.

@nickvergessen 
Is it hard to add the timestamp for the event? Could I implement it in the activitiy notification with some help of you?

**Comment by nickvergessen** [comment]
I don't have time to dive into the DAV code again any time soon.
