### ISSUE TITLE
Configuration/Activation

### ISSUE THREAD

**Issue by ironiff** [nickv-nextcloud/event_update_notification#20]
Who can explain how to configure the plugin.
- I installed NextCloud (20) on shared Hosting (goneo.de). 
- email configuration is OK (test Email is receiving my email address)
- cron job (webCron) is running every 5 min. (e.g. backups are created as expected)
... but I do not receive any notifications after adding an event on shared calendar.
Thank you in advance.
ironiff

**Comment by nickvergessen** [comment]
You don't receive them for your own actions. Only for the actions of other people

**Comment by ironiff** [comment]
Thank you for feedback. This is correct. I forgot to add, popup notifications are working correctly (for other people, yes), but not the push notifications on smartphone (ios/Android)

**Comment by nickvergessen** [comment]
You need the Nextcloud Files app installed (from google play not fdroid)

**Comment by ironiff** [comment]
Danke schön @nickvergessen  :-) that solved the issue. now it is fine
