### ISSUE TITLE
Add transifex

### ISSUE THREAD

**Issue by nickvergessen** [nickv-nextcloud/event_update_notification#3]
If it doesnt mean we have to move to nextcloud/

**Comment by nickvergessen** [comment]
@MorrisJobke any idea?

**Comment by MorrisJobke** [comment]
Yes works - please add @nextcloud-bot as contributor (and as admin to be allowed to push directly to protected branches) and then I will add it as cron job.

**Comment by MorrisJobke** [comment]
fix is in https://github.com/nickv-nextcloud/event_update_notification/pull/4

**Comment by nickvergessen** [comment]
Added

**Comment by MorrisJobke** [comment]
There it is: https://www.transifex.com/nextcloud/nextcloud/event_update_notification/
